#!/usr/bin/env python3
"""Turn a psychrometric-card config into Home Assistant template sensors.

The card computes absolute humidity, dew point and enthalpy for its own display and
forgets them on every redraw. A Lovelace card cannot create entities, so recording those
values means recomputing them in Home Assistant. This writes that YAML for you, from the
same sensor list the card already carries -- three sensors per temperature/humidity pair,
which is not something anyone should type by hand.

    python3 tools/generate_template_sensors.py card.yaml >> template.yaml

card.yaml is the card's own configuration (or anything containing its `sensors:` list).
Also copy custom_templates/psychrometrics.jinja into <config>/custom_templates/, then call
the homeassistant.reload_custom_templates and template.reload services -- no restart.

Options:
    --prefix P     unique_id prefix                     (default: psychro)
    --labels a,b,c suffixes appended to each sensor name
                   (default: "absolute humidity,dew point,enthalpy")
"""

import argparse
import re
import sys
import unicodedata

try:
    import yaml
except ImportError:
    sys.exit("pyyaml is required: pip install pyyaml")

HEADER = """# Psychrometrics -- values derived from each temperature/humidity pair.
#
# Generated by tools/generate_template_sensors.py from the psychrometric-card config.
# The formulas live in custom_templates/psychrometrics.jinja, imported below.
"""


def slug(name):
    plain = unicodedata.normalize("NFKD", name).encode("ascii", "ignore").decode()
    return re.sub(r"_+", "_", re.sub(r"[^a-z0-9]+", "_", plain.lower())).strip("_")


def entry(name, uid, unit, state, availability, extra="", comment=""):
    out = ['    - name: "%s"' % name.replace('"', '\\"'),
           "      unique_id: %s" % uid,
           '      unit_of_measurement: "%s"' % unit]
    if extra:
        out.append(extra)
    out.append("      state_class: measurement")
    if comment:
        out.append(comment)
    out.append("      availability: >")
    out.append("        %s" % availability)
    out.append("      state: >")
    out.append("        %s" % state)
    return "\n".join(out)


def main():
    p = argparse.ArgumentParser()
    p.add_argument("config", help="YAML file holding the card config")
    p.add_argument("--prefix", default="psychro")
    p.add_argument("--labels", default="absolute humidity,dew point,enthalpy")
    args = p.parse_args()

    with open(args.config, encoding="utf-8") as fh:
        cfg = yaml.safe_load(fh)
    sensors = cfg.get("sensors") if isinstance(cfg, dict) else None
    if not sensors:
        sys.exit("no `sensors:` list found in %s" % args.config)
    labels = [s.strip() for s in args.labels.split(",")]
    if len(labels) != 3:
        sys.exit("--labels needs exactly three comma-separated suffixes")

    print(HEADER)
    print("- sensor:")
    for s in sensors:
        name = s.get("name") or s["temperature"]
        t, h = s["temperature"], s["humidity"]
        sl = slug(name)
        both = "{{ has_value('%s') and has_value('%s') }}" % (t, h)
        print(entry(
            "%s %s" % (name, labels[0]), "%s_%s_absolute_humidity" % (args.prefix, sl),
            "g/kg",
            "{%% from 'psychrometrics.jinja' import absolute_humidity %%}\n"
            "        {{ absolute_humidity(states('%s') | float, states('%s') | float) }}" % (t, h),
            both))
        print(entry(
            "%s %s" % (name, labels[1]), "%s_%s_dew_point" % (args.prefix, sl),
            "°C",
            "{%% from 'psychrometrics.jinja' import dew_point %%}\n"
            "        {{ dew_point(states('%s') | float, states('%s') | float) }}" % (t, h),
            "{{ has_value('%s') and has_value('%s')\n"
            "           and 0 <= states('%s') | float(-99) <= 60 }}" % (t, h, t),
            extra="      device_class: temperature",
            comment="      # Magnus-Tetens only holds from 0 to 60 C: outside it the sensor\n"
                    "      # reports unavailable rather than a plausible-looking number."))
        print(entry(
            "%s %s" % (name, labels[2]), "%s_%s_enthalpy" % (args.prefix, sl),
            "kJ/kg",
            "{%% from 'psychrometrics.jinja' import enthalpy %%}\n"
            "        {{ enthalpy(states('%s') | float, states('%s') | float) }}" % (t, h),
            both))


if __name__ == "__main__":
    main()
